=== xawt/Szkolenie_XML/wersja_prowadzacego/03-dtd/sklep3.dtd
<!ELEMENT sklep (towar*)>

<!ELEMENT towar (nazwa, cena, opis?, cena-promocyjna*)>

<!ELEMENT nazwa (#PCDATA)>
<!ELEMENT cena (#PCDATA)>
<!ELEMENT cena-promocyjna (#PCDATA)>

<!ENTITY % Tekst "#PCDATA | em | link | br | inny-towar"> 

<!ELEMENT opis (%Tekst;)* >

<!ELEMENT em (%Tekst;)*>
<!ELEMENT link (%Tekst;)*>
<!ELEMENT br EMPTY>
<!ELEMENT inny-towar EMPTY>

<!ATTLIST inny-towar id IDREF #REQUIRED>


<!ATTLIST towar
	id ID #REQUIRED
	id-kategorii CDATA #IMPLIED
>

<!ATTLIST cena-promocyjna
	od CDATA #REQUIRED
	do CDATA #IMPLIED
>

<!ATTLIST link href CDATA #REQUIRED>

=== xawt/Szkolenie_XML/wersja_prowadzacego/03-dtd/sklep3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sklep SYSTEM "sklep3.dtd" >
<sklep>
  <towar id="T1" id-kategorii="herbata">
    <nazwa>Lipton 50 szt.</nazwa>
    <cena>8.75</cena>
    <opis>
    	Mniejsza paczka herbaty niż <inny-towar id="T2"/>
    </opis>
  </towar>
  
  <towar id="T2" id-kategorii="herbata">
    <nazwa>Lipton 100 szt.</nazwa>
    <cena>15</cena>
    <opis>
    	Większa paczka herbaty niż <inny-towar id="T7"/>
    </opis>
  </towar>
  
  <towar id="T2" id-kategorii="kawa">
    <nazwa>Kawa Jacobs</nazwa>
    <cena>15</cena>
    <opis>
    </opis>
  </towar>
</sklep>
