=== xawt/Szkolenie_XML/wersja_prowadzacego/03-dtd/sklep.dtd
<!ELEMENT sklep (towar*)>

<!ELEMENT towar (nazwa, cena, opis?, cena-promocyjna*)>

<!ELEMENT nazwa (#PCDATA)>
<!ELEMENT cena (#PCDATA)>
<!ELEMENT cena-promocyjna (#PCDATA)>

<!ELEMENT opis (#PCDATA | em | link | br)* >
<!ELEMENT em (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT br EMPTY>

<!ATTLIST towar
	id CDATA #REQUIRED
	id-kategorii CDATA #IMPLIED
>

<!ATTLIST cena-promocyjna
	od CDATA #REQUIRED
	do CDATA #IMPLIED
>

<!ATTLIST link href CDATA #REQUIRED>

=== xawt/Szkolenie_XML/wersja_prowadzacego/03-dtd/sklep1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sklep SYSTEM "sklep.dtd" >
<sklep>
  <towar id="123">
  	<nazwa>Mleko</nazwa>
  	<cena>2.50</cena>
  	<opis>
  		Mleko jest dobre <em>ale nie dla każdego</em>.<br/>
  		Druga linia. <link href="http://pl.wikipedia.org/wiki/mleko">zob. także artykuł</link>
  	</opis>
  </towar>

  <towar id="124">
  	<nazwa>Obiad</nazwa>
  	<cena>21.50</cena>
    <opis>Ala ma kota. <em>pierwsze wyróżnienie</em> <em>drugie wyróżnienie</em></opis>
    <cena-promocyjna od="2017-10-15" do="2017-10-20">10.99</cena-promocyjna>
  </towar>
  
</sklep>
