=== xawt/Szkolenie_XML/wersja_prowadzacego/04-schema/osoby4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
			targetNamespace="http://vavatech.pl/osoby4"
			xmlns:tns="http://vavatech.pl/osoby4">
	
	<xs:element name="osoba">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="imie" type="xs:string" maxOccurs="3"/>
				<xs:element name="nazwisko" type="xs:string"/>
				<xs:element name="data-urodzenia" type="xs:date" minOccurs="0"/>

				<!-- Odwołanie się do globalnej definicji elementu -->
				<xs:element ref="tns:adres"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<!-- Globalna definicja elementu. -->
	<xs:element name="adres">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ulica" type="xs:string"/>
				<xs:element name="nr-domu" type="xs:string"/>
				<xs:element name="nr-mieszkania" type="xs:string" minOccurs="0"/>
				<xs:element name="kod-pocztowy" type="xs:string"/>
				<xs:element name="miejscowosc" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== xawt/Szkolenie_XML/wersja_prowadzacego/04-schema/osoby4a.xml
<?xml version="1.0" encoding="UTF-8"?>
<osoba xmlns="http://vavatech.pl/osoby4"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://vavatech.pl/osoby4 osoby4.xsd ">
	
<!-- Ten dokument się  nie waliduje, gdyż zgodnie ze schematem 4 element imie nie powinien należeć do NS, a należy z powodu domyślnej przestrzeni nazw -->
  <imie>imie</imie>
  <nazwisko>nazwisko</nazwisko>
  <data-urodzenia>2001-01-01</data-urodzenia>
  <adres>
    <ulica>ulica</ulica>
    <nr-domu>nr-domu</nr-domu>
    <nr-mieszkania>nr-mieszkania</nr-mieszkania>
    <kod-pocztowy>kod-pocztowy</kod-pocztowy>
    <miejscowosc>miejscowosc</miejscowosc>
  </adres>
</osoba>

=== xawt/Szkolenie_XML/wersja_prowadzacego/04-schema/osoby4.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:osoba xmlns:p="http://vavatech.pl/osoby4" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://vavatech.pl/osoby4 osoby4.xsd ">
  <imie>imie</imie>
  <nazwisko>nazwisko</nazwisko>
  <data-urodzenia>2001-01-01</data-urodzenia>
  <p:adres>
    <ulica>ulica</ulica>
    <nr-domu>nr-domu</nr-domu>
    <nr-mieszkania>nr-mieszkania</nr-mieszkania>
    <kod-pocztowy>kod-pocztowy</kod-pocztowy>
    <miejscowosc>miejscowosc</miejscowosc>
  </p:adres>
</p:osoba>
