=== xawt/Szkolenie_XML/wersja_prowadzacego/08-schema_klucze/sklep.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.vavatech.pl/sklep"
	xmlns:tns="http://www.vavatech.pl/sklep"
	elementFormDefault="qualified">
	
	<element name="sklep">
		<complexType>
			<sequence>
				<element ref="tns:kategoria" minOccurs="0" maxOccurs="unbounded"/>
				<element ref="tns:towar" minOccurs="0" maxOccurs="unbounded"/>
			</sequence>
		</complexType>
		
		<key name="KluczKategorii">
			<selector xpath="tns:kategoria"/>
			<field xpath="@numer"/>
		</key>
		<keyref name="TowaryDoKategorii" refer="tns:KluczKategorii">
			<selector xpath="tns:towar"/>
			<field xpath="@numer-kategorii"></field>
		</keyref>
	</element>
	
	<element name="kategoria">
		<complexType>
			<sequence>
				<element name="nazwa" type="tns:Nazwa"/>
				<element name="opis" type="tns:Tekst" minOccurs="0"/>
			</sequence>
			<attribute name="numer" type="int"/>
		</complexType>
	</element>
	
	<element name="towar">
		<complexType>
			<sequence>
				<element name="nazwa" type="tns:Nazwa"/>
				<element name="cena" type="tns:Cena"/>
				<element name="vat" type="tns:Vat"/>
				<element name="cena-promocyjna" type="tns:CenaPromocyjna"
					minOccurs="0" maxOccurs="unbounded"/>
				<element name="opis" type="tns:Tekst"/>
			</sequence>
			<attribute name="id" type="int"/>
			<attribute name="numer-kategorii" type="int"/>
		</complexType>
	</element>
		
	<complexType name="CenaPromocyjna">
		<simpleContent>
			<extension base="decimal">
				<attribute name="od" type="date" use="required"/>
				<attribute name="do" type="date" use="optional"/>
			</extension>
		</simpleContent>
	</complexType>
	
	<complexType name="Tekst" mixed="true">
		<choice minOccurs="0" maxOccurs="unbounded">
			<element name="em" type="tns:Tekst"/>
			<element name="link" type="tns:Link"/>
			<element name="br">
				<complexType/> <!-- pusta zawartosc -->
			</element>
		</choice>
	</complexType>
	
	<complexType name="Link">
		<complexContent>
			<extension base="tns:Tekst">
				<attribute name="href" type="anyURI"/>
			</extension>
		</complexContent>
	</complexType>
	
	<simpleType name="Nazwa">
		<restriction base="string">
			<minLength value="1"/>
			<maxLength value="40"/>
		</restriction>
	</simpleType>
	
	<simpleType name="Cena">
		<restriction base="decimal">
			<fractionDigits value="2"/>
		</restriction>
	</simpleType>

	<simpleType name="Vat">
		<restriction base="int">
			<enumeration value="0"/>
			<enumeration value="5"/>
			<enumeration value="8"/>
			<enumeration value="23"/>
		</restriction>
	</simpleType>
</schema>

=== xawt/Szkolenie_XML/wersja_prowadzacego/06-schema_sklep/sklep1.xml
<?xml version="1.0" encoding="UTF-8"?>
<s:sklep xmlns:s="http://www.vavatech.pl/sklep" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.vavatech.pl/sklep sklep.xsd ">
  <s:towar id="2">
    <s:nazwa>Pralka</s:nazwa>
    <s:cena>1999</s:cena>
    <s:vat>23</s:vat>
    <s:opis>Opis pralki</s:opis>
  </s:towar>

  <s:towar id="7">
    <s:nazwa>Odkurzacz</s:nazwa>
    <s:cena>349</s:cena>
    <s:vat>23</s:vat>
    <s:opis>Opis okurzacza</s:opis>
  </s:towar>
</s:sklep>

=== xawt/Szkolenie_XML/wersja_prowadzacego/08-schema_klucze/sklep.xml
<?xml version="1.0" encoding="UTF-8"?>
<sklep xmlns="http://www.vavatech.pl/sklep" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.vavatech.pl/sklep sklep.xsd ">
  <kategoria numer="2">
    <nazwa>AGD</nazwa>
    <opis>
    </opis>
  </kategoria>

  <kategoria numer="4">
    <nazwa>RTV</nazwa>
    <opis>
    </opis>
  </kategoria>

  <towar id="0" numer-kategorii="4">
    <nazwa>nazwa</nazwa>
    <cena>0.0</cena>
    <vat>0</vat>
    <cena-promocyjna do="2001-01-01" od="2001-01-01">0.0</cena-promocyjna>
    <opis>
    </opis>
  </towar>
</sklep>
